### ISSUE TITLE
"Unable to find a suitable version for angular"

### ISSUE THREAD

**Issue by LeonardoMinati** [johnpapa/generator-hottowel#100]
I begin to use this generator today and when i tried to scaffold a new app the generator gave me this error: 
![immagine](https://cloud.githubusercontent.com/assets/9377944/8283705/14d96d42-18f9-11e5-8e28-1afbd9ce52e3.png)

is this my pc? in this case, how do i solve it? If not hope it helps to improve this generator. :smile:

**Comment by attilacsanyi** [comment]
This can happen during the time while adding/upgrading new libraries or just call **bower update** which can pull down newer versions while your bower.json remains untouched.
*This is not because hottowel, but due to transitive dependency resolution process within bower.*

Just add another section to your **bower.json** where you can restrict the version you like during bower install for example:
```json
    "resolutions": {
        "angular": "v1.3.16"
    }
```

**Comment by johnpapa** [comment]
yep
