### ISSUE TITLE
Uglify in gulp build is breaking my state resolve in ui-router

### ISSUE THREAD

**Issue by joanrodriguez** [johnpapa/generator-hottowel#133]
I have a state with a resolve function and while it works fine in dev, uglify breaks it in gulp build.

The result is a blank page with no error in the console and nothing loading, quiet hard to debug.

By adding {mangle: false} in uglify options I was able to fix it, but it kinds of defeats the purpose.

Here is my state:

    {
      state: 's',
      config: {
         url: '/secure',
          abstract: true,
          templateUrl: 'app/layout/shell.html',
          controller: 'ShellController',
          controllerAs: 'vm',
          resolve: {
            authenticated: function($auth, $q, $location) {
              var deferred = $q.defer();
              if (!$auth.isAuthenticated()) {
                window.localStorage.loginRedirect = $location.path();
                $location.path('');
              } else {
                deferred.resolve();
              }
              return deferred.promise;
            }
          }                
      }
    }

Any other suggestions?

**Comment by ssbrewster** [comment]
What does that part of the minified/uglified code look like?

**Comment by u0m3** [comment]
Check out this section https://github.com/johnpapa/angular-styleguide#style-y092

When your minify your code, your anonymous function get's also minified and angular does can not resolve dependency injection because the parameter names do not match anything it knows and it has no hints as to what they might be.

My suggestion would be to use a named function and either use ng-annotate annotations or manual dependency injection (look around the link I gave you, a few sections back - if I remember correctly - this topic is covered).

**Comment by johnpapa** [comment]
yep you need to handle the minification of the app https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#minification-and-annotation
