### ISSUE TITLE
font-awesome does not load when using gulp-serve-build

### ISSUE THREAD

**Issue by xxryan1234** [johnpapa/generator-hottowel#159]
anybody know how to resolve this issue?

**Comment by nuKs** [comment]
I think I got through the same issue.

In my memory, font awesome injects bower scss.

in gulp.config.js: make sure font contains 
```js
bower.directory + 'font-awesome/fonts/**/*.{eot,svg,ttf,woff,woff2}'
```

You can inject font awesome scss using
```scss
$fa-font-path: "PATH_TO_YOUR_FONT_DIR_FROM_BUILD";
// bower:scss
@import "../../bower_components/font-awesome/scss/font-awesome.scss";
// endbower
```

Another solution is to overrides fontawesome bower main in your bower.json to grasp the .css instead of the .scss. You'll have then to inject it in your html and to build it in the same directory as the fonts and to update the gulpfile to inject the font css.
```html
    <!-- build:css fonts/fonts.css -->
    <!-- inject:fonts:css -->
    <!-- endinject -->
    <!-- endbuild -->
```

Not sure it is the same issue though.

**Comment by mouthzipper** [comment]
Just add font-awesome in bower.json overrides;
"overrides": {
    "font-awesome": {
        "main": "css/font-awesome.css"
    }
}`

**Comment by xxryan1234** [comment]
thanks guys!
