### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by lowmemory** [johnpapa/generator-hottowel#21]
Inside the function hideSplash() (shell.controller.js) there is a timeout of 1 sec with the intention of waiting 1 sec to see the splash screen. But if you change it to 20 sec. (20000) nothing change and the spash screen remains only few moments as before.
bye.

Marco

**Comment by yevk** [comment]
This is because the splash `div` element exists in **index.html** and has `ng-show="false"`. So it actually disappears only when Angular loads and processes `ng-show` to add the `ng-hide` class to the element.

What needs to be done is move the whole splash `div` block to the end (inside) of the main `div` in **layout/shell.html** and change `ng-show="false"` to `ng-show="vm.showSplash"`.
