### ISSUE TITLE
gulp-csso is no longer being maintained

### ISSUE THREAD

**Issue by mattpwest** [johnpapa/generator-hottowel#88]
Hi John,

Thanks for the great template and style guide!

I just ran into an issue with a project we generated from the template where gulp-csso was choking on a large client-provided CSS file that we were including in the project. After some investigation I found that the underlying issue had already been reported to the [csso](https://github.com/css/csso) project that [gulp-csso](https://github.com/ben-eb/gulp-csso) builds on in 2014.

It looks like csso is not being actively maintained anymore, so please consider getting rid of gulp-csso in favor of something that is better maintained?

I was able to get past the hurdle by switching our project to [gulp-minify-css](https://github.com/jonathanepollack/gulp-minify-css) which builds on [clean-css](https://github.com/jakubpawlowicz/clean-css). Clean-css seems to perform pretty well in [benchmarks](http://goalsmashers.github.io/css-minification-benchmark/) and appears to be actively maintained, so that may be a good alternative.

I'd be happy to submit a pull request if that would help.

**Comment by johnpapa** [comment]
Feel free to make the pr. 


John Papa




On Wed, May 20, 2015 at 1:12 AM -0700, "Matt Van Der Westhuizen" <notifications@github.com> wrote:












Hi John,



Thanks for the great template and style guide!



I just ran into an issue with a project we generated from the template where gulp-csso was choking on a large client-provided CSS file that we were including in the project. After some investigation I found that the underlying issue had already been reported to the csso project that gulp-csso builds on in 2014.



It looks like csso is not being actively maintained anymore, so please consider getting rid of gulp-csso in favor of something that is better maintained?



I was able to get past the hurdle by switching our project to gulp-minify-css which builds on clean-css. Clean-css seems to perform pretty well in benchmarks and appears to be actively maintained, so that may be a good alternative.



I'd be happy to submit a pull request if that would help.
