### ISSUE TITLE
You don't seem to have a generator with the name hottowel installed

### ISSUE THREAD

**Issue by jkruer01** [johnpapa/generator-hottowel#93]
I followed the install steps but when I run yo hottowel helloWorld it gives me the message "You don't seem to have a generator with the name hottowel installed."

**Comment by jkruer01** [comment]
Just an FYI...I'm running on Windows 7.  Here is my output:

Your environment has been set up for using Node.js 0.12.4 (x64) and npm.

C:\Users\kruerj>npm install -g bower gulp nodemon
C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js
C:\Program Files\nodejs\nodemon -> C:\Program Files\nodejs\node_modules\nodemon\bin\nodemon.js
C:\Program Files\nodejs\bower -> C:\Program Files\nodejs\node_modules\bower\bin\bower
gulp@3.9.0 C:\Program Files\nodejs\node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── v8flags@2.0.7 (user-home@1.1.1)
├── tildify@1.1.0 (os-homedir@1.0.0)
├── semver@4.3.6
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.5 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, object-a
ssign@2.1.1, replace-ext@0.0.1, vinyl@0.4.6, lodash.template@3.6.1, through2@0.6.5, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

nodemon@1.3.7 C:\Program Files\nodejs\node_modules\nodemon
├── minimatch@0.3.0 (sigmund@1.0.1, lru-cache@2.6.4)
├── touch@0.0.3 (nopt@1.0.10)
├── ps-tree@0.0.3 (event-stream@0.5.3)
└── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, chalk@1.0.0, semver-diff@2.0.0, latest-version@1.0.0, configstore@0.3.2)

bower@1.4.1 C:\Program Files\nodejs\node_modules\bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── chmodr@0.1.0
├── user-home@1.1.1
├── abbrev@1.0.7
├── rimraf@2.4.0
├── archy@1.0.0
├── bower-logger@0.2.2
├── graceful-fs@3.0.8
├── bower-endpoint-parser@0.2.2
├── lru-cache@2.6.4
├── lockfile@1.0.1
├── opn@1.0.2
├── retry@0.6.1
├── nopt@3.0.2
├── tmp@0.0.24
├── request-progress@0.3.1 (throttleit@0.0.2)
├── q@1.4.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── semver@2.3.2
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── which@1.1.1 (is-absolute@0.1.7)
├── fstream@1.0.6 (inherits@2.0.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promptly@0.2.0 (read@1.0.6)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── insight@0.5.3 (object-assign@2.1.1, lodash.debounce@3.1.0, async@0.9.2, os-name@1.0.3, tough-cookie@0.12.1)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── tar-fs@1.5.1 (pump@1.0.0, tar-stream@1.2.0)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── request@2.53.0 (caseless@0.9.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, json-stringi
fy-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.14, bl@0.9.4, http-signature@0.10.1, tough-cookie@2.0.0, hawk@2
.3.1)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── github@0.2.4 (mime@1.3.4)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, osenv@0.1.2, uuid@2.0.1, js-yaml@3.3.1)
├── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.7, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.3)
└── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)

C:\Users\kruerj>npm update

C:\Users\kruerj>npm install -g generator-hottowel
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-hottowel will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-hottowel@0.2.14 C:\Program Files\nodejs\node_modules\generator-hottowel
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@0.3.0 (ansi-regex@0.2.1, string-length@0.1.2, ansi-styles@1.1.0, pad-component@0.0.1, word-wrap@0.1.3, strip-ansi@0.2.2, minimist@0.2.0, chalk@0.4.0,
taketalk@0.1.1)
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, rimraf@2.4.0, text-table@0.2.0, underscore.string@2.4.0, mime@1.3.
4, async@0.9.2, debug@1.0.4, grouped-queue@0.3.0, shelljs@0.3.0, mkdirp@0.5.1, nopt@3.0.2, cross-spawn@0.2.9, run-async@0.1.0, iconv-lite@0.4.10, findup-sync@0.
1.3, file-utils@0.2.2, glob@4.5.3, github-username@1.1.1, download@1.0.7, lodash@2.4.2, request@2.58.0, cheerio@0.17.0, gruntfile-editor@0.2.0, inquirer@0.7.3)

C:\Users\kruerj>mkdir myapp

C:\Users\kruerj>cd myapp

C:\Users\kruerj\myapp>yo hottowel helloWorld
Error hottowel helloWorld

You don't seem to have a generator with the name hottowel installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.

C:\Users\kruerj\myapp>

**Comment by johnpapa** [comment]
This is all node and npm help. Stackoverflow would be better.

That said .... run `yo` by itself. see what generators it lists. if its not there then I am guessing the global package for generator-hottowel either did not install or it installed in the wrong place. then try `npm list -g --depth=0` to see all global npmpackages. if its not there, it did not install. If it is there and yo cannot find it, first run `yo doctor` which helps fix minor issue with yo. If that all fails, you need to take a closer look at ho you set up node and the npm package folder.

**Comment by bartvanderwal** [comment]
:+1. I worked round it with local instead of global install as mentioned in #107:

    npm install generator-hottowel

**Comment by robertmazzo** [comment]
I had the same exact problem. I use NVM node package mgr, and installed node 0.12 and latest 6.5. I get the message using either node version. That is,

 yo hottowel angular-test returns message "You don't seem to have a generator with the name hottowel installed."
So I removed the -g global flag as suggested by @bartvanderwal , and it is now generating my app.
However, there are plenty of deprecated warnings:

npm WARN package.json angular-test@0.0.0 No repository field.
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN engine plato@1.7.0: wanted: {"node":">= 4.4.5"} (current: {"node":"0.12
.0","npm":"2.5.1"})
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
\
